# Generated by Django 5.0.4 on 2024-04-10 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=455)),
                ('image', models.ImageField(upload_to='authors/')),
                ('description', models.TextField()),
                ('email', models.CharField(max_length=455)),
                ('phone', models.CharField(max_length=455)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455)),
                ('banner_image', models.ImageField(upload_to='banner-images/')),
                ('intro_video', models.TextField()),
                ('course_time', models.CharField(max_length=455)),
                ('description', models.TextField()),
                ('students_count', models.CharField(max_length=455)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.category')),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455)),
                ('video', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('material', models.FileField(blank=True, null=True, upload_to='files/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.section')),
            ],
        ),
        migrations.CreateModel(
            name='LessonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455)),
                ('image', models.ImageField(upload_to='lesson-images/')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='course_app.lesson')),
            ],
        ),
    ]
