# Generated by Django 5.0.4 on 2024-04-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0007_remove_lesson_course_alter_lesson_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'Avtorlar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name_plural': "Bo'lim mavzulari"},
        ),
        migrations.AlterModelOptions(
            name='lessonimage',
            options={'verbose_name_plural': 'Mavzu rasmlari'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name_plural': "Kurs bo'limlari"},
        ),
    ]
